# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df270a87967bc52c85d3e51b7999e2e9aecac2e185457cdd82b17ab0b3ed9453e8c4106822e565c3a1326599d25fd4dbd68fcad925caabafee6dcc8565dcc20b

test:
  secret_key_base: 98fe1cab462eb75edd07075d90169a5cbda0bdb812f4f28f8cebe567914b132c2c5c5e6104027a0073ae3ab336d5fbf000d6045f147ec96bfc9b330850ec8850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
